#!/bin/bash
### BEGIN INIT INFO
# Provides:          EzRegistratio
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: EzRegistration Thrift service
# Description:       EzRegistration Thrift service
### END INIT INFO

# Source function library.
. /etc/init.d/functions
export EZBAKE_ENCRYPTION_SECRET=$(runuser ezsecurity -l sh -c 'echo ${EZBAKE_ENCRYPTION_SECRET}')

servicename=EzRegistration
RETVAL=0
LOCKFILE=/var/lock/subsys/${servicename}
PIDFILE=/opt/ezregistration/${servicename}.pid

EZ_PREFIX=/opt/ezregistration
EZ_USER=ezsecurity

SERVICE_NAME=EzSecurityRegistration
SERVICE_ID=_Ez_Registration
SERVICE_CLASS=ezbake.security.service.registration.handler.EzSecurityRegistrationHandler
SSL_DIR=/opt/ezregistration/etc/ezbake/pki

PORT=30200
THRIFT_RUNNER_JAR="/opt/ezbake/thriftrunner/bin/thriftrunner.jar"
THRIFT_RUNNER_OPTS="-j ${EZ_PREFIX}/lib/ezregistration.jar \
          -c ${SERVICE_CLASS} -x ${SERVICE_ID} \
	      -p ${PORT} -s ${SERVICE_NAME} \
          -D ezbake.shared.secret.environment.variable=EZBAKE_ENCRYPTION_SECRET \
	      -D ezbake.security.app.id=${SERVICE_ID} \
	      -D ezbake.security.ssl.dir=${SSL_DIR}"

JAVA_OPTS="-jar ${THRIFT_RUNNER_JAR} ${THRIFT_RUNNER_OPTS}"

STETHOSCOPE_CLIENT="/opt/ezbake/ezbake-discovery-stethoscope-client/ezbake-discovery-stethoscope-client.jar"
STETHOSCOPE="java -jar $STETHOSCOPE_CLIENT \
-D ezbake.security.ssl.dir=${SSL_DIR} \
-D service.name=${SERVICE_NAME} \
-D application.name=common_services \
--private-service-hostname $(hostname) \
--private-service-port ${PORT} \
--public-service-hostname $(hostname) \
--public-service-port ${PORT} \
--checkin-interval "5" &> /tmp/EzSecurityRegistration/stethoscope.log"

start() {
	echo -n "Starting ${servicename}: "

	daemon --user $EZ_USER --pidfile ${PIDFILE} "cd \"${EZ_PREFIX}\" && { ${STETHOSCOPE} & java ${JAVA_OPTS} ; } &>/dev/null & echo \$! > ${PIDFILE}"
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $LOCKFILE

	echo
	return $RETVAL
}

stop() {
	echo -n "Shutting down ${servicename}: "
	pkill -P $(<${PIDFILE}) && success || failure
	RETVAL=$?
	rm -f $PIDFILE
	rm -f $LOCKFILE
	echo
	return $RETVAL
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	echo -n "Status of ${servicename}: "
	PID=`cat "$PIDFILE"`
	if [ -f "$PIDFILE" -a -d "/proc/${PID}" ]; then
		echo -n "running"
		RETVAL=0
	elif [ -f "$LOCKFILE" ]; then
		echo -n "dead"
		RETVAL=2
	else
		echo -n "dead"
		RETVAL=3
	fi
	echo
	;;
    restart)
    	stop
	start
	;;
    reload)
	#<cause the service configuration to be reread, either with
	#kill -HUP or by restarting the daemons, in a manner similar
	#to restart above>
	;;
    *)
	echo "Usage: ${servicename} {start|stop|status|reload|restart}"
	exit 1
	;;
esac
exit $RETVAL


